type: T2 # S[N], T[N]
model: enc_dec # dec_only
dim: 3
dx: 0.01
dt: 0.01
t_batch_size: 1
seed: 42

cnf:
  flow_num_layers: 2
  mlp_num_layers: 2
  hidden_size: 16
  num_bins: 5

train:
  epochs: 10000
  lr: 0.001
  _lambda: 5000.
  batch_size: 2048
  eval_frequency: 100
