hydra:
  output_subdir: null  
  run:
    dir: .

general:
  type: rwpo # ot, rwpo, fp
  dim: 2
  dx: 0.01
  dt: 0.01
  t_batch_size: 10
  seed: 42

ot:

rwpo:
  T: 1
  beta: 1
  a: 1
  pot_mode: double-well # quadratic, double-well

fp:
  T: 1
  a: 1 # drift coeff
  sigma: 1/2

cnf:
  flow_num_layers: 2
  mlp_num_layers: 2
  hidden_size: 16
  num_bins: 5

train:
  epochs: 30000
  lr: 0.001
  batch_size: 2048
  test_batch_size: 2000
  eval_frequency: 100
