hydra:
  output_subdir: null  
  run:
    dir: .

general:
  dim: 10
  case: ot # ot, rwpo, fk
  seed: 42

ot:

rwpo:
  T: 1
  beta: 1
  pot_mode: quadratic # quadratic, double-well

fk:
  T: 1
  a: 1 # drift coeff
  sigma: 1/2

train:
  epochs: 30000
  lr: 0.001
  batch_size: 2048
  t_batch_size: 1
