hydra:
  output_subdir: null  
  run:
    dir: .

general:
  type: rwpo # ot, rwpo, fp
  dim: 2
  dx: 0.01
  dt: 0.01
  t_batch_size: 1
  seed: 42

ot:
  subtype: free # free, obstacle

rwpo:
  T: 2
  beta: 10
  a: 1
  pot_type: double_well # quadratic, double_well

fp:
  T: 1
  a: 1 # drift coeff
  sigma: .5
  velocity_field_type: gradient # gradient, nongradient, lorenz

cnf:
  flow_num_layers: 2
  mlp_num_layers: 2
  hidden_size: 16
  num_bins: 5

train:
  epochs: 30000
  lr: 0.001
  _lambda: 5000.
  batch_size: 2048
  eval_frequency: 100
